// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pared9 = new Entity("Pared")
engine.addEntity(pared9)
const pared9transform = new Transform({
  position: new Vector3(51.25, 0.75, 63.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
pared9.addComponentOrReplace(pared9transform)
const pared9GLTFShape = new GLTFShape("models/Pared.glb")
pared9GLTFShape.withCollisions = true
pared9GLTFShape.isPointerBlocker = true
pared9GLTFShape.visible = true
pared9.addComponentOrReplace(pared9GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pared10 = new Entity("Pared")
engine.addEntity(pared10)
const pared10transform = new Transform({
  position: new Vector3(26.75, 0.75, 63.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
pared10.addComponentOrReplace(pared10transform)
pared10.addComponentOrReplace(pared9GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pared11 = new Entity("Pared")
engine.addEntity(pared11)
const pared11transform = new Transform({
  position: new Vector3(12.75, 0.75, 63.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
pared11.addComponentOrReplace(pared11transform)
pared11.addComponentOrReplace(pared9GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pared12 = new Entity("Pared")
engine.addEntity(pared12)
const pared12transform = new Transform({
  position: new Vector3(63.5, 0.75, 51.25),
  rotation: new Quaternion(0, 0.7071066, 0, 0.707107),
  scale: new Vector3(1, 1, 1)
})
pared12.addComponentOrReplace(pared12transform)
pared12.addComponentOrReplace(pared9GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pared13 = new Entity("Pared")
engine.addEntity(pared13)
const pared13transform = new Transform({
  position: new Vector3(63.5, 0.75, 26.75),
  rotation: new Quaternion(0, 0.7071066, 0, 0.707107),
  scale: new Vector3(1, 1, 1)
})
pared13.addComponentOrReplace(pared13transform)
pared13.addComponentOrReplace(pared9GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pared14 = new Entity("Pared")
engine.addEntity(pared14)
const pared14transform = new Transform({
  position: new Vector3(63.5, 0.75, 12.75),
  rotation: new Quaternion(0, 0.7071066, 0, 0.707107),
  scale: new Vector3(1, 1, 1)
})
pared14.addComponentOrReplace(pared14transform)
pared14.addComponentOrReplace(pared9GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pared15 = new Entity("Pared")
engine.addEntity(pared15)
const pared15transform = new Transform({
  position: new Vector3(0.5, 0.75, 51.25),
  rotation: new Quaternion(0, -0.7071066, 0, 0.707107),
  scale: new Vector3(1, 1, 1)
})
pared15.addComponentOrReplace(pared15transform)
pared15.addComponentOrReplace(pared9GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pared16 = new Entity("Pared")
engine.addEntity(pared16)
const pared16transform = new Transform({
  position: new Vector3(0.5, 0.75, 26.25),
  rotation: new Quaternion(0, -0.7071066, 0, 0.707107),
  scale: new Vector3(1, 1, 1)
})
pared16.addComponentOrReplace(pared16transform)
pared16.addComponentOrReplace(pared9GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pared17 = new Entity("Pared")
engine.addEntity(pared17)
const pared17transform = new Transform({
  position: new Vector3(0.5, 0.75, 12.75),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1, 1, 1)
})
pared17.addComponentOrReplace(pared17transform)
pared17.addComponentOrReplace(pared9GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pared18 = new Entity("Pared")
engine.addEntity(pared18)
const pared18transform = new Transform({
  position: new Vector3(51.25, 0.75, 0.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
pared18.addComponentOrReplace(pared18transform)
pared18.addComponentOrReplace(pared9GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pared19 = new Entity("Pared")
engine.addEntity(pared19)
const pared19transform = new Transform({
  position: new Vector3(12.75, 0.75, 0.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
pared19.addComponentOrReplace(pared19transform)
pared19.addComponentOrReplace(pared9GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const piso21 = new Entity("Piso")
engine.addEntity(piso21)
const piso21transform = new Transform({
  position: new Vector3(62.75491, 0.01516533, 0.1412506),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(2.489754, 1, 2.549069)
})
piso21.addComponentOrReplace(piso21transform)
const piso21GLTFShape = new GLTFShape("models/Piso.glb")
piso21GLTFShape.withCollisions = true
piso21GLTFShape.isPointerBlocker = true
piso21GLTFShape.visible = true
piso21.addComponentOrReplace(piso21GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY




export let scene = {
}

