// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const piso21 = new Entity("Piso")
engine.addEntity(piso21)
const piso21transform = new Transform({
  position: new Vector3(30.83686, 0, -5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.227167, 0.4928873, 1.436701)
})
piso21.addComponentOrReplace(piso21transform)
const piso21GLTFShape = new GLTFShape("models/Piso.glb")
piso21GLTFShape.withCollisions = true
piso21GLTFShape.isPointerBlocker = true
piso21GLTFShape.visible = true
piso21.addComponentOrReplace(piso21GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const flores228 = new Entity("flores 2")
engine.addEntity(flores228)
const flores228transform = new Transform({
  position: new Vector3(8.5, 0.1672406, 8.75),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.6783227, 0.6783227, 0.6933383)
})
flores228.addComponentOrReplace(flores228transform)
const flores228GLTFShape = new GLTFShape("models/flores 2.glb")
flores228GLTFShape.withCollisions = true
flores228GLTFShape.isPointerBlocker = true
flores228GLTFShape.visible = true
flores228.addComponentOrReplace(flores228GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const flores229 = new Entity("flores 2")
engine.addEntity(flores229)
const flores229transform = new Transform({
  position: new Vector3(23.33467, 0.1672406, 8.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.5914137, 0.5914137, 0.6549169)
})
flores229.addComponentOrReplace(flores229transform)
flores229.addComponentOrReplace(flores228GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const flores230 = new Entity("flores 2")
engine.addEntity(flores230)
const flores230transform = new Transform({
  position: new Vector3(8.342591, 0.1749597, 25.52596),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.6596639, 0.6596639, 0.5995118)
})
flores230.addComponentOrReplace(flores230transform)
flores230.addComponentOrReplace(flores228GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const flores231 = new Entity("flores 2")
engine.addEntity(flores231)
const flores231transform = new Transform({
  position: new Vector3(23.45382, 0.1672406, 23.75),
  rotation: new Quaternion(0, -0.7125154, 0, 0.7016565),
  scale: new Vector3(0.5699023, 0.5699023, 0.5699023)
})
flores231.addComponentOrReplace(flores231transform)
flores231.addComponentOrReplace(flores228GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pared236 = new Entity("Pared 2")
engine.addEntity(pared236)
const pared236transform = new Transform({
  position: new Vector3(15.45312, 0.9460869, 0.37361),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.201305, 1, 1)
})
pared236.addComponentOrReplace(pared236transform)
const pared236GLTFShape = new GLTFShape("models/Pared 2.glb")
pared236GLTFShape.withCollisions = true
pared236GLTFShape.isPointerBlocker = true
pared236GLTFShape.visible = true
pared236.addComponentOrReplace(pared236GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pared237 = new Entity("Pared 2")
engine.addEntity(pared237)
const pared237transform = new Transform({
  position: new Vector3(30.10993, 0.9326324, 15.75),
  rotation: new Quaternion(0, 0.7071066, 0, 0.707107),
  scale: new Vector3(1.246449, 1, 1)
})
pared237.addComponentOrReplace(pared237transform)
pared237.addComponentOrReplace(pared236GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pared238 = new Entity("Pared 2")
engine.addEntity(pared238)
const pared238transform = new Transform({
  position: new Vector3(0.8897152, 0.9424222, 15.7222),
  rotation: new Quaternion(0, 0.7071066, 0, 0.707107),
  scale: new Vector3(1.251719, 1, 1)
})
pared238.addComponentOrReplace(pared238transform)
pared238.addComponentOrReplace(pared236GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pared239 = new Entity("Pared 2")
engine.addEntity(pared239)
const pared239transform = new Transform({
  position: new Vector3(15.3679, 0.9409933, 31.07378),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.195681, 1, 1)
})
pared239.addComponentOrReplace(pared239transform)
pared239.addComponentOrReplace(pared236GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const arbol245 = new Entity("Arbol 2")
engine.addEntity(arbol245)
const arbol245transform = new Transform({
  position: new Vector3(23.99257, 3.57504, 8.984301),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.5151527, 0.5151527, 0.5151527)
})
arbol245.addComponentOrReplace(arbol245transform)
const arbol245GLTFShape = new GLTFShape("models/Arbol 2.glb")
arbol245GLTFShape.withCollisions = true
arbol245GLTFShape.isPointerBlocker = true
arbol245GLTFShape.visible = true
arbol245.addComponentOrReplace(arbol245GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const arbol246 = new Entity("Arbol 2")
engine.addEntity(arbol246)
const arbol246transform = new Transform({
  position: new Vector3(5.703235, 3.599062, 22.13055),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.5205349, 0.5205349, 0.5205349)
})
arbol246.addComponentOrReplace(arbol246transform)
arbol246.addComponentOrReplace(arbol245GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const puente50 = new Entity("Puente")
engine.addEntity(puente50)
const puente50transform = new Transform({
  position: new Vector3(12.69826, 1.662062, 3.205059),
  rotation: new Quaternion(0, 0.7171434, 0, -0.6969257),
  scale: new Vector3(1, 1, 1)
})
puente50.addComponentOrReplace(puente50transform)
const puente50GLTFShape = new GLTFShape("models/Puente.glb")
puente50GLTFShape.withCollisions = true
puente50GLTFShape.isPointerBlocker = true
puente50GLTFShape.visible = true
puente50.addComponentOrReplace(puente50GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pueste253 = new Entity("Pueste  2")
engine.addEntity(pueste253)
const pueste253transform = new Transform({
  position: new Vector3(13, 1.5, -1),
  rotation: new Quaternion(0, 0.7071074, 0, -0.7071062),
  scale: new Vector3(1, 1, 1)
})
pueste253.addComponentOrReplace(pueste253transform)
const pueste253GLTFShape = new GLTFShape("models/Pueste  2.glb")
pueste253GLTFShape.withCollisions = true
pueste253GLTFShape.isPointerBlocker = true
pueste253GLTFShape.visible = true
pueste253.addComponentOrReplace(pueste253GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY




export let scene = {
}

